# Generated by Django 4.0.3 on 2022-03-17 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='NameExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('status', models.IntegerField()),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.authuser')),
            ],
            options={
                'db_table': 'lib_extension_name',
            },
        ),
        migrations.CreateModel(
            name='CivilStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_name', models.CharField(max_length=128, unique=True)),
                ('status', models.IntegerField()),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.authuser')),
            ],
            options={
                'verbose_name_plural': 'Civil Status',
                'db_table': 'lib_civil_status',
            },
        ),
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_name', models.CharField(max_length=128, unique=True)),
                ('status', models.IntegerField()),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.authuser')),
            ],
            options={
                'verbose_name_plural': 'Blood Type',
                'db_table': 'lib_blood_type',
            },
        ),
    ]
