# Generated by Django 4.0.3 on 2022-03-17 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_authuser_alter_province_options_nameextension_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={},
        ),
    ]
