# Generated by Django 4.0.3 on 2022-03-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_province_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nameextension',
            table='lib_extensionname',
        ),
    ]
