# Generated by Django 4.0.3 on 2022-03-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_nameextension_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nameextension',
            table='lib_extension_name',
        ),
    ]
