# Generated by Django 4.0.3 on 2022-03-17 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_nameextension_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAppStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('acronym', models.CharField(max_length=64, unique=True)),
                ('status', models.BooleanField()),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.authuser')),
            ],
            options={
                'db_table': 'tbl_employee_status',
            },
        ),
        migrations.CreateModel(
            name='EmployeeFundSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('acronym', models.CharField(max_length=64, unique=True)),
                ('status', models.BooleanField()),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.authuser')),
            ],
            options={
                'db_table': 'tbl_employee_fund_source',
            },
        ),
        migrations.CreateModel(
            name='EmployeePersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=64)),
                ('gender', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=11)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=11)),
                ('is_filipino', models.IntegerField()),
                ('is_dual_citizenship', models.IntegerField()),
                ('dc_by_birth', models.IntegerField()),
                ('dc_by_naturalization', models.IntegerField()),
                ('mobile_no', models.CharField(max_length=13)),
                ('telephone_no', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=128)),
                ('image', models.FileField(default='picture/default.jpg', upload_to='pictures/')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.authuser')),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.bloodtype')),
                ('civil_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.civilstatus')),
                ('ext_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.nameextension')),
            ],
            options={
                'db_table': 'tbl_employee_personalinfo',
            },
        ),
        migrations.CreateModel(
            name='EmployeeUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=255)),
                ('salary_grade', models.CharField(max_length=255)),
                ('salary_rate', models.CharField(max_length=255)),
                ('emp_division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.division')),
                ('emp_fund', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.employeefundsource')),
                ('emp_pos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.position')),
                ('emp_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.section')),
                ('emp_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.employeeappstatus')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.employeepersonalinfo')),
            ],
            options={
                'db_table': 'tbl_employee_user_details',
            },
        ),
    ]
